# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0

module(
    name = "xff_mime_db",
    version = "0.0.0",
)

bazel_dep(name = "rules_cc", version = "0.2.25")
bazel_dep(name = "xff_extras_api", version = "0.0.0")
bazel_dep(name = "platforms", version = "1.1.0")

bazel_dep(name = "googletest", version = "1.18.0.bcr.1")
