# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0

"""Build rule for embedding and registering an authoritative license body.

The formatter-clean generated C++ is checked in so every Bazel configuration compiles the same
source path. The genrule produces an independent candidate and the paired diff test rejects drift
from the authoritative license text. Because the output depends only on `src`, `spdx`, and this
macro, it is invariant across the host OS, architecture, and target configuration.
"""

load("@mboworks_mbo//mbo/diff:diff.bzl", "diff_test")
load("@rules_cc//cc:defs.bzl", "cc_library")

def license_body(name, spdx, src):
    """Embeds an authoritative license and verifies its checked-in C++ mirror.

    Args:
        name: Bazel target name and prefix for the checked-in generated source.
        spdx: SPDX identifier registered for the embedded license body.
        src: Authoritative license-text label.
    """
    generated = name + "_generated.cc"
    candidate = name + "_generated.actual.cc"
    native.genrule(
        name = name + "_gen",
        srcs = [src],
        outs = [candidate],
        cmd = """(
          echo '// Generated by license_body() from its license source. Do not edit.'
          echo '#include "xff/license/notice.h"'
          echo
          echo 'namespace xff::license {'
          echo 'namespace {'
          echo 'const LicenseBodyRegistrar kBody{{'
          printf '    .spdx = "%s",\n' '""" + spdx + """'
          echo '    .text ='
          printf '        R"xff_license('
          cat $(location """ + src + """)
          printf ')xff_license",\n}};\n'
          echo '}  // namespace'
          echo '}  // namespace xff::license'
        ) > $@""",
    )
    cc_library(
        name = name,
        srcs = [generated],
        deps = ["@xff_extras_api//:license_notice_cc"],
        alwayslink = True,
    )
    diff_test(
        name = name + "_generated_test",
        file_new = candidate,
        file_old = generated,
    )
